# Generated by Django 5.2.5 on 2025-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_cargo_alter_funcionario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
