# Generated by Django 5.2.5 on 2025-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_epi_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='status',
            field=models.CharField(choices=[('fornecido', 'Fornecido'), ('em uso', 'Em uso'), ('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='fornecido', max_length=20),
        ),
    ]
